In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
df = pd.DataFrame(scores,
             columns = ["國文","英文","地理","人文","氣候"],
             index=[f"stu{i}" for i in range(1,51)]
)
df['國文']
df['英文']
df[['國文','地理']]
df

        國文  英文  地理   人文   氣候
stu1    65  67  86   84   74
stu2    69  79  63   96   69
stu3    62  65  95   66   69
stu4    93  74  78   94   64
stu5    82  76  66   69   56
stu6    66  97  99   88   98
stu7    67  77  53   50   74
stu8    71  86  79   94   76
stu9    77  51  72   53   86
stu10   69  99  82   86   97
stu11   62  87  73   89   63
stu12   79  79  99   81   88
stu13   96  89  96   90   53
stu14   62  50  98   95   86
stu15   96  99  78   83   50
stu16   66  72  98   63   88
stu17   66  52  59   99   85
stu18   82  67  50   77   86
stu19   60  94  67   94   54
stu20   94  81  94   68   53
stu21   99  98  54   55   54
stu22   60  87  63   57   51
stu23   78  73  92   91   58
stu24   61  51  94   73   98
stu25   60  60  99   78  100
stu26   87  92  84   97   52
stu27   95  66  98   61   71
stu28   76  63  73   70   88
stu29   59  86  52   52   98
stu30   72  83  87   50   57
stu31   52  59  76  100   64
stu32  100  74  71   79   57
stu33   56  51  71   93   70
stu34   82  76  60   62   83
stu35   89  62  69   80   68
stu36   80  84  97   63   61
stu37   66  95  61   99   89
stu38   60  86  75   68   60
stu39   51  94  76   62   66
stu40   72  98  61   68   50
stu41   76  52  67   78   63
stu42   95  78  74   69   99
stu43   91  74  61   72   68
stu44   63  52  66   90   54
stu45   56  85  95   56   94
stu46   62  74  96   99   58
stu47   76  82  54   73   87
stu48   77  89  67  100   55
stu49   93  61  84   57   83
stu50   89  74  62   65   62

In [2]:
df.loc['stu1']
df.loc[['stu1','stu50']]

       國文  英文  地理  人文  氣候
stu1   65  67  86  84  74
stu50  89  74  62  65  62

In [3]:
sum = df['國文'] + df['英文'] + df['地理'] + df['人文'] + df['氣候']
df['總分'] = sum
mean = sum / 5
df['平均'] = mean
df

        國文  英文  地理   人文   氣候   總分    平均
stu1    65  67  86   84   74  376  75.2
stu2    69  79  63   96   69  376  75.2
stu3    62  65  95   66   69  357  71.4
stu4    93  74  78   94   64  403  80.6
stu5    82  76  66   69   56  349  69.8
stu6    66  97  99   88   98  448  89.6
stu7    67  77  53   50   74  321  64.2
stu8    71  86  79   94   76  406  81.2
stu9    77  51  72   53   86  339  67.8
stu10   69  99  82   86   97  433  86.6
stu11   62  87  73   89   63  374  74.8
stu12   79  79  99   81   88  426  85.2
stu13   96  89  96   90   53  424  84.8
stu14   62  50  98   95   86  391  78.2
stu15   96  99  78   83   50  406  81.2
stu16   66  72  98   63   88  387  77.4
stu17   66  52  59   99   85  361  72.2
stu18   82  67  50   77   86  362  72.4
stu19   60  94  67   94   54  369  73.8
stu20   94  81  94   68   53  390  78.0
stu21   99  98  54   55   54  360  72.0
stu22   60  87  63   57   51  318  63.6
stu23   78  73  92   91   58  392  78.4
stu24   61  51  94   73   98  377  75.4
stu25   60  60  99   78  100  397  79.4
stu26   87  92  84   97   52  412  82.4
stu27   95  66  98   61   71  391  78.2
stu28   76  63  73   70   88  370  74.0
stu29   59  86  52   52   98  347  69.4
stu30   72  83  87   50   57  349  69.8
stu31   52  59  76  100   64  351  70.2
stu32  100  74  71   79   57  381  76.2
stu33   56  51  71   93   70  341  68.2
stu34   82  76  60   62   83  363  72.6
stu35   89  62  69   80   68  368  73.6
stu36   80  84  97   63   61  385  77.0
stu37   66  95  61   99   89  410  82.0
stu38   60  86  75   68   60  349  69.8
stu39   51  94  76   62   66  349  69.8
stu40   72  98  61   68   50  349  69.8
stu41   76  52  67   78   63  336  67.2
stu42   95  78  74   69   99  415  83.0
stu43   91  74  61   72   68  366  73.2
stu44   63  52  66   90   54  325  65.0
stu45   56  85  95   56   94  386  77.2
stu46   62  74  96   99   58  389  77.8
stu47   76  82  54   73   87  372  74.4
stu48   77  89  67  100   55  388  77.6
stu49   93  61  84   57   83  378  75.6
stu50   89  74  62   65   62  352  70.4

In [4]:
df.iloc[-10:,:5]

       國文  英文  地理   人文  氣候
stu41  76  52  67   78  63
stu42  95  78  74   69  99
stu43  91  74  61   72  68
stu44  63  52  66   90  54
stu45  56  85  95   56  94
stu46  62  74  96   99  58
stu47  76  82  54   73  87
stu48  77  89  67  100  55
stu49  93  61  84   57  83
stu50  89  74  62   65  62